### ISSUE TITLE
Make the syntax checker work with syntastic

### ISSUE THREAD

**Issue by svenstaro** [petRUShka/vim-opencl#3]
You are advertising syntastic support but that can't actually work right now as it is because it doesn't register in syntastic. Have a look [here](https://github.com/rust-lang/rust.vim/blob/master/syntax_checkers/rust/rustc.vim) on how you can easily provide external syntax checker support for syntastic.

**Comment by petRUShka** [comment]
@svenstaro, have you seen that file: https://github.com/petRUShka/vim-opencl/blob/master/syntax_checkers/opencl.vim ?

It is responsible for Synstastic support. How do you find that it opencl checker isn't registered as Syntastic checker?

Please, tell me:

1. What does say `clcc` on your `cl`-file?
2. What `ft` of your file in vim? (to check this use `:se ft` inside vim)

**Comment by svenstaro** [comment]
clcc compiles my cl file and ft says it's `opencl`. I believe you have to tell syntastic about your checker by doing something like the rust file does:

```
call g:SyntasticRegistry.CreateAndRegisterChecker({
    \ 'filetype': 'rust',
    \ 'name': 'rustc'})
```

**Comment by petRUShka** [comment]
May be you are right. At the time of writing that file its content was enought. The plugin was well tested. My guess, Syntastic chahnged the way of registering checkers. I havn't updated synstastic for a long time. 

Unfortunately right now I can't test functionality of plugin. What do you think about testing it yourself and sending the pull request?
